// Generated by Xata Codegen 0.30.1. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "noticias",
    checkConstraints: {
      noticias_xata_id_length_xata_id: {
        name: "noticias_xata_id_length_xata_id",
        columns: ["xata_id"],
        definition: "CHECK ((length(xata_id) < 256))",
      },
    },
    foreignKeys: {
      imagen_link: {
        name: "imagen_link",
        columns: ["imagen"],
        referencedTable: "noticias",
        referencedColumns: ["xata_id"],
        onDelete: "SET NULL",
      },
    },
    primaryKey: [],
    uniqueConstraints: {
      _pgroll_new_noticias_xata_id_key: {
        name: "_pgroll_new_noticias_xata_id_key",
        columns: ["xata_id"],
      },
    },
    columns: [
      {
        name: "articulo",
        type: "text",
        notNull: false,
        unique: false,
        defaultValue: null,
        comment: "",
      },
      {
        name: "imagen",
        type: "link",
        link: { table: "noticias" },
        notNull: false,
        unique: false,
        defaultValue: null,
        comment: '{"xata.link":"noticias"}',
      },
      {
        name: "resumen",
        type: "text",
        notNull: false,
        unique: false,
        defaultValue: null,
        comment: "",
      },
      {
        name: "tags",
        type: "multiple",
        notNull: false,
        unique: false,
        defaultValue: null,
        comment: "",
      },
      {
        name: "titulo",
        type: "text",
        notNull: false,
        unique: false,
        defaultValue: null,
        comment: "",
      },
      {
        name: "xata_createdat",
        type: "datetime",
        notNull: true,
        unique: false,
        defaultValue: "now()",
        comment: "",
      },
      {
        name: "xata_id",
        type: "text",
        notNull: true,
        unique: true,
        defaultValue: "('rec_'::text || (xata_private.xid())::text)",
        comment: "",
      },
      {
        name: "xata_updatedat",
        type: "datetime",
        notNull: true,
        unique: false,
        defaultValue: "now()",
        comment: "",
      },
      {
        name: "xata_version",
        type: "int",
        notNull: true,
        unique: false,
        defaultValue: "0",
        comment: "",
      },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Noticias = InferredTypes["noticias"];
export type NoticiasRecord = Noticias & XataRecord;

export type DatabaseSchema = {
  noticias: NoticiasRecord;
};


const DatabaseClient = buildClient();

const defaultOptions = {
  apiKey: import.meta.env.PUBLIC_XATA_API_KEY,
  databaseURL: import.meta.env.PUBLIC_XATA_DATABASE_URL,
  branch: import.meta.env.PUBLIC_XATA_BRANCH,
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
